### ISSUE TITLE
Model becomes manifold when adding tabs

### ISSUE THREAD

**Issue by Phlipinator** [5axes/TabAntiWarping#26] opened 2023-11-17 16:05 UTC
I have just today encountered the issue that more often than not when adding tabs the model will get marked as manifold (see picture below).
![Screenshot 2023-11-17 170259](https://github.com/5axes/TabAntiWarping/assets/57066673/ae124cc0-31c6-4bea-8f13-3eaefd3e45c7)
I have no idea what caused this issue, but it makes it nearly impossible to place the tabs now.
They also just get displaced all over the built plate even though I clicked on the model.

I have since tested it with Cura 5.2.2 and its working fine there.

I have already tried:
- Adding different models to see if it maybe was an issue of the STL
- Re-installing the plugin

**Comment by 5axes** [comment] 2023-11-17 16:53
Share one of your Project, Absolutly no issue on my side. Check when you clic to add a tab if one is not define outside of the build plate.

**Comment by Phlipinator** [comment] 2023-11-17 16:56
Here is a random project.
Everything is definitely inside the build volume. 
[Antiwarp Tab problem.zip](https://github.com/5axes/TabAntiWarping/files/13394612/Antiwarp.Tab.problem.zip)

**Comment by 5axes** [comment] 2023-11-17 16:59
As I say check if your tab is not created outside of the buildplate ... That's the case  
![image](https://github.com/5axes/TabAntiWarping/assets/11015345/f5cd0cdc-cb84-4dc3-99d5-9190bf85a8d9)

**Comment by 5axes** [comment] 2023-11-17 17:02
I doesn't have any issue. I'm going to close the Issue unless there are further indications of other problems.

![image](https://github.com/5axes/TabAntiWarping/assets/11015345/6323f2c1-8f40-4973-9c92-7bb256f35f4b)

**Comment by Phlipinator** [comment] 2023-11-17 17:04
I see, I haven't checked that far out, sorry.

Still this happens when I click on the model as I did usually.

**Comment by Phlipinator** [comment] 2023-11-17 17:05
Then the issue may needs to be renamed to something like "Tab gets placed way out of build volume when clicking on model".

Thank you for the quick response.

**Comment by 5axes** [comment] 2023-11-17 17:10
Yes but I cannot reproduce this issue.

**Comment by Phlipinator** [comment] 2023-11-17 17:12
Hmm.
I will try installing Cura on a different machine and see if I can replicate it there.
However, I do know of a friend of mine who has had the same issue (at least I assume it's the same, since I didn't know the tab was placed so far out of the volume)

**Comment by 5axes** [comment] 2023-11-17 17:22
I know it's possible because I've had this problem before. But when I try to reproduce it, it never works.   The only solution if the part becomes not slicable after putting a Tab . CTRL+Z to undo the last action in Cura.

**Comment by Phlipinator** [comment] 2023-11-17 17:24
Ah okay, I understand.
Yes, I have been doing it like that as well.
Then I'll close this issue now?

Weirdly it doesn't seem to happen with old Cura versions.

**Closed as completed** 2024-01-15 20:11 UTC
Labels: Type : Invalid, Status : Need infos
